### ISSUE TITLE
New game for 0451 Vault: Guardians of the Galaxy

### ISSUE THREAD

**Issue by kynapse** [SuiMachine/SuiMachine.github.io#4]
The first code in the Guardians of the Galaxy game is 0451. The game was developed by Eidos Montreal.
<img width="1920" alt="Screenshot 2022-03-28 011009" src="https://user-images.githubusercontent.com/8743241/160330265-4089b6b2-3b22-40d6-90cf-96bdac02ec05.png">

**Comment by SuiMachine** [comment]
Right. Finally added it - was told about it already by one person. Thanks.
